import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UserContextProvider } from '@/context/userContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserContextProvider>
      <body className={`${inter.className}`}>{children}</body>
      </UserContextProvider>
    </html>
  )
}
